2023-11-28 22:00:42.427 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.432 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.435 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration manish which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.439 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plex_assistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.443 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.446 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ourgroceries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.452 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.457 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalinfo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.462 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration car_wash which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.468 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration saver which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.473 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.476 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.484 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration favicon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.491 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration temperature_feels_like which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.498 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration illuminance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.512 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.531 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.533 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.541 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration simpleicons which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.546 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.549 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.552 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration worlds_air_quality_index which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.558 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.561 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_photos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.565 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration n26 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.565 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'n26' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2023-11-28 22:00:42.569 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration whatspie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.573 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lg_hombot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.578 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pollenprognos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.582 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration jokes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.585 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:42.589 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-28 22:00:55.817 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-11-28 22:00:56.199 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=428 from 2023-11-25 14:14:00.295063)
2023-11-28 22:01:14.438 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-11-28 22:01:18.464 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:01:18.973 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}'
2023-11-28 22:01:18.974 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:02:05.448 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: samsungtv, tankerkoenig, buienradar, openweathermap, hacs, media_player.samsungtv, plex, ffmpeg, sensor.buienradar, weather.buienradar, androidtv_remote, version, google_assistant, sensor.anniversaries, wake_on_lan
2023-11-28 22:02:07.036 ERROR (SyncWorker_0) [glocaltokens.client] [!] Could not get access token.
2023-11-28 22:02:38.132 WARNING (MainThread) [custom_components.plex_assistant.const] Plex Assistant: No Plex servers available. Ensure that you've setup the HA Plex integration and the server is reachable. 
2023-11-28 22:02:42.178 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1925, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1626, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified
2023-11-28 22:02:42.201 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.desk_temp_adj'
2023-11-28 22:02:42.203 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1925, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1626, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified
2023-11-28 22:02:42.212 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.front_door_sensor_device_temperature_adj'
2023-11-28 22:02:42.214 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1925, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1626, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified
2023-11-28 22:02:42.222 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.living_room_window_sensor_device_temperature_adj'
2023-11-28 22:02:42.223 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_level }}'
2023-11-28 22:02:42.224 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.battery_level }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2266, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2263, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-11-28 22:02:42.238 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-11-28 22:02:42.240 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.battery_icon }}) renders=3>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2266, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2263, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-11-28 22:02:42.249 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_level }}'
2023-11-28 22:02:42.251 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-11-28 22:02:42.252 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.battery_level }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.hombot_battery'
2023-11-28 22:02:42.252 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.battery_icon }}) renders=5>' for attribute '_attr_icon' in entity 'sensor.hombot_battery'
2023-11-28 22:02:42.745 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.status }}'
2023-11-28 22:02:42.745 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.status }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2266, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2263, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-11-28 22:02:42.754 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.status }}'
2023-11-28 22:02:42.754 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.status }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.hombot_status'
2023-11-28 22:02:42.759 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1944, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1626, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified
2023-11-28 22:02:42.767 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified') while processing template 'Template<template=({% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.medicine_time_recent'
2023-11-28 22:02:43.361 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Living rooms - lights on when blinds close' trigger: In 'numeric_state' condition: entity cover.living_room_blinds state 'closed' cannot be processed as a number
2023-11-28 22:02:43.362 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-28 22:02:44.180 WARNING (MainThread) [custom_components.hacs] You have 'ericpignet/home-assistant-lg_hombot' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Integration is missing a version, and is abandoned.)
2023-11-28 22:02:53.677 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_rain (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-11-28 22:02:53.677 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_snow (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-11-28 22:02:53.678 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.home_precipitation (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-11-28 22:03:24.236 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:03:24.245 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:03:24.248 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:03:24.648 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:03:24.677 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:03:24.759 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 22:05:19.849 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:05:19.850 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:06:24.221 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-28 22:09:19.861 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:09:19.863 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:13:19.839 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:13:19.841 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:17:19.862 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:17:19.864 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:21:19.824 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:21:19.826 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:25:19.864 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:25:19.866 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:29:19.870 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:29:19.871 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:33:19.864 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:33:19.866 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:37:19.866 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:37:19.867 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:41:19.842 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:41:19.843 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:45:19.890 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:45:19.892 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:49:19.877 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:49:19.878 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:53:19.886 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:53:19.889 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 22:57:19.883 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 22:57:19.884 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:01:19.832 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:01:19.834 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:03:25.001 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:03:25.011 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:03:25.101 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:05:19.875 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:05:19.876 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:09:19.882 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:09:19.884 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:13:19.867 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:13:19.869 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:17:19.901 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:17:19.902 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:21:19.853 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:21:19.855 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:25:19.875 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:25:19.877 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:29:19.866 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:29:19.868 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:31:50.314 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:31:50.593 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:33:19.884 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:33:19.885 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:37:19.917 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:37:19.919 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:37:19.952 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.plex_recently_added fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/plex_recently_added/sensor.py", line 255, in async_update
    for lib_section in libraries['MediaContainer']['Directory']:
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'MediaContainer'
2023-11-28 23:41:12.945 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-28 23:41:19.867 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:41:19.869 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:45:19.902 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:45:19.904 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:49:19.873 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:49:19.875 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:53:19.871 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:53:19.872 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-28 23:56:10.505 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:56:10.824 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-28 23:57:19.879 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-28 23:57:19.880 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:01:19.852 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:01:19.854 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:05:19.897 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:05:19.898 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:09:19.908 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:09:19.909 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:13:19.948 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:13:19.953 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:17:19.924 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:17:19.926 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:21:19.871 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:21:19.872 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:25:19.899 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:25:19.900 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:29:19.902 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:29:19.903 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:31:50.920 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 00:31:51.323 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 00:33:19.897 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:33:19.899 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:37:19.906 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:37:19.908 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:41:19.876 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:41:19.877 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:44:43.620 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-29 00:45:19.895 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:45:19.897 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:49:19.897 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:49:19.899 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:53:19.889 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:53:19.891 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 00:57:19.902 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 00:57:19.903 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:01:15.970 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:01:16.324 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:01:19.980 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:01:19.981 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:05:19.891 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:05:19.893 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:09:19.925 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:09:19.926 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:13:19.918 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:13:19.920 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:17:19.964 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:17:19.965 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:18:53.869 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'closed' cannot be processed as a number
2023-11-29 01:18:53.871 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:54.531 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:54.535 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:55.275 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:55.278 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:55.400 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:55.403 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:55.855 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:55.858 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:56.310 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:56.313 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:56.733 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:56.735 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:57.182 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:57.185 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:57.641 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:57.645 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:58.102 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:58.104 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:58.510 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:58.513 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:58.972 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:58.975 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:59.375 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:59.377 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:18:59.837 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:18:59.840 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:00.302 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:19:00.304 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:00.721 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:19:00.725 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:01.176 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:19:01.180 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:01.631 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:19:01.634 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:02.099 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'open' cannot be processed as a number
2023-11-29 01:19:02.102 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:19:02.504 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'closed' cannot be processed as a number
2023-11-29 01:19:02.507 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Bedroom - open window detection':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity binary_sensor.openclose_13
2023-11-29 01:20:01.792 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-29 01:21:22.120 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:21:22.122 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:24:56.780 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:24:57.091 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:25:15.362 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:25:15.667 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 01:25:19.903 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:25:19.905 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:29:19.910 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:29:19.912 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:31:34.278 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-29 01:33:19.922 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:33:19.925 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:37:19.930 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:37:19.931 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:39:52.351 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2023-11-29 01:39:52.352 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_tv is taking over 10 seconds
2023-11-29 01:41:19.900 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:41:19.901 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:45:19.938 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:45:19.940 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:48:00.874 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 01:49:19.957 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:49:19.959 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:51:12.707 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 01:51:45.916 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-11-29 01:52:30.003 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 01:53:19.923 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:53:19.924 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 01:55:23.114 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 01:57:19.910 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 01:57:19.912 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:01:16.341 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:01:16.665 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:01:19.897 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:01:19.899 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:01:44.093 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:03:09.859 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:05:19.938 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:05:19.939 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:06:23.183 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:09:19.944 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:09:19.945 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:13:19.927 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:13:19.929 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:14:17.456 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:16:57.255 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:17:19.941 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:17:19.943 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:20:06.415 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 02:21:19.943 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:21:19.945 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:24:57.106 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:24:57.470 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:25:15.682 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:25:16.013 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:25:19.929 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:25:19.931 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:29:19.934 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:29:19.935 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:30:51.618 ERROR (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.113):32190] Error reading from socket.
2023-11-29 02:30:51.619 WARNING (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.113):32190] Error communicating with socket, resetting connection
2023-11-29 02:30:51.627 ERROR (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.113):32190] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.113', 32190)), retrying in 5.0s
2023-11-29 02:31:19.691 WARNING (Thread-9) [pychromecast.socket_client] [Bedroom(192.168.69.113):8009] Heartbeat timeout, resetting connection
2023-11-29 02:31:26.987 ERROR (Thread-9) [pychromecast.socket_client] [Bedroom(192.168.69.113):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.113', 8009)), retrying in 5.0s
2023-11-29 02:31:32.053 ERROR (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.221):32190] Error reading from socket.
2023-11-29 02:31:32.054 WARNING (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.221):32190] Error communicating with socket, resetting connection
2023-11-29 02:31:34.324 ERROR (Thread-10) [pychromecast.socket_client] [Both rooms(192.168.69.113):32190] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.113', 32190)), retrying in 5.0s
2023-11-29 02:33:19.922 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:33:19.923 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:37:19.960 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:37:19.961 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:41:19.903 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:41:19.904 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:45:19.928 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:45:19.931 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:49:19.950 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:49:19.951 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:53:19.923 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:53:19.924 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 02:56:10.484 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:56:10.816 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 02:57:19.963 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 02:57:19.965 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:01:19.918 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:01:19.920 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:05:19.929 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:05:19.931 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:09:19.947 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:09:19.949 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:13:19.926 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:13:19.928 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:17:19.943 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:17:19.944 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:21:19.910 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:21:19.912 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:25:19.929 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:25:19.931 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:29:19.902 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:29:19.904 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:33:19.922 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:33:19.925 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:37:19.936 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:37:19.938 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:41:10.508 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 03:41:10.817 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-11-29 03:41:19.924 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:41:19.925 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:45:19.952 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:45:19.954 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:49:19.949 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:49:19.950 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:53:19.932 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:53:19.934 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 03:57:19.940 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 03:57:19.942 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:01:19.926 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:01:19.927 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:05:19.934 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:05:19.936 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:09:19.941 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:09:19.943 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:13:19.941 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:13:19.943 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:17:19.946 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:17:19.948 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:21:19.934 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:21:19.935 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:25:19.946 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:25:19.948 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:29:19.966 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:29:19.968 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:33:19.950 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:33:19.952 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:37:19.962 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:37:19.964 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:41:19.945 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:41:19.947 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:42:59.003 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 04:45:19.943 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:45:19.945 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:48:15.056 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 04:49:19.996 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:49:19.998 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:49:39.408 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-11-29 04:53:19.959 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:53:19.960 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-11-29 04:57:19.996 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-11-29 04:57:19.997 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
